version: '3.8'

services:
  db:
    image: mongo:5.0.3
    logging:
      driver: none
    ports:
      - '27017:27017'
  mongoExpress:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
